export const FETCH_PARTIES = 'FETCH_PARTIES';
export const RECEIVE_PARTIES = 'RECEIVE_PARTIES';
export const CHANGE_CURRENT_PARTIE = 'CHANGE_CURRENT_PARTIE';
export const FETCH_PARTIE_ARTICLES = 'FETCH_PARTIE_ARTICLES';
export const SET_VIEW = 'SET_VIEW';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
